name: selenium_demo
on: [push]

jobs:
  selenium-tests:
    runs-on: ubuntu-latest
    env:
      CORRECT_PASSWORD: ${{ secrets.CORRECT_PASSWORD }}
      INVALID_PASSWORD: ${{ secrets.INVALID_PASSWORD }}


    steps:
      - uses: actions/checkout@v3

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      # install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi


      #Run tests
      - name: Run Selenium tests
        run: |
          mkdir -p tests/reports
          pytest tests/test_login.py --browser=chrome --html=tests/reports/automation-report-chrome.html


      # Upload test report as artifact
      - name: Upload test report
        uses: actions/upload-artifact@v4
        with:
          name: test-report
          path: tests/reports/
