name: selenium_demo
on: [push]

jobs:
  selenium-tests:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        browser: [ chrome, firefox ]

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          

      # Install browsers if needed
      - name: Install browsers
        run: |
          if [ "${{matrix.browser}}" = "firefox" ]; then
            sudo apt-get update && sudo apt-get install -y firefox
          fi
          

      #Run tests
      - name: Run Selenium tests
        run: |
          mkdir -p tests/reports
          pytest tests/test_login.py \
            --browser=${{ matrix.browser }} \
            --html=tests/reports/${{ matrix.browser }}-report.html

      # Upload test report as artifact
      - name: Upload test report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-report-${{ matrix.browser }}
          path: tests/reports/${{ matrix.browser }}-report.html
